function createfigure(X1, Y1, Y2, Y3, Y4, Y5, Y6)
%CREATEFIGURE(X1, Y1, Y2, Y3, Y4, Y5, Y6)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data
%  Y4:  vector of y data
%  Y5:  vector of y data
%  Y46:  vector of y data

%  Auto-generated by MATLAB on 15-Jul-2020 10:39:26

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create subplot
subplot1 = subplot(6,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1);

% Create title
title('Raw');

% Create subplot
subplot2 = subplot(6,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X1,Y2,'Parent',subplot2);

% Create title
title('Highpass Filter');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-2 2]);
% Create subplot
subplot3 = subplot(6,1,3,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(X1,Y3,'Parent',subplot3);

% Create title
title('Abs Value (all channels)');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[-2 2]);
% Create subplot
subplot4 = subplot(6,1,4,'Parent',figure1);
hold(subplot4,'on');

% Create plot
plot(X1,Y4,'Parent',subplot4);

% Create title
title('Binary Mask of Abs Value > 1 uV');

% Create subplot
subplot5 = subplot(6,1,5,'Parent',figure1);
hold(subplot5,'on');

% Create plot
plot(X1,Y5,'Parent',subplot5);

% Create title
title('Rolling Mean of Binary Mask');

% Create subplot
subplot6 = subplot(6,1,6,'Parent',figure1);
hold(subplot6,'on');

% Create plot
plot(X1,Y6,'Parent',subplot6);
xlabel('Time (s)')

% Create title
title('Data Masked Rolling Mean > 0.001');

